### ISSUE TITLE
When would "Analyze Your Vectors (To Be Written)" section be finished?

### ISSUE THREAD

**Issue by peoplecure** [conjugateprior/cbn#3]
Hello there :)

Thanks for the nice instructions on how to replicate your study. It's really helpful and saves me _a lot_ of time. I was wondering when I can expect the **Analyze Your Vectors** section to be complete? I'm looking forward to comparing my method with the original creator's 👍

**Comment by conjugateprior** [comment]
Right about now, since you ask. 

See https://conjugateprior.github.io/cbn/articles/using_your_own_vectors.html for a bit more detail on how to do it.

**Comment by peoplecure** [comment]
For some reason, the newly updated version looks almost exactly the same as the previous one!

**Comment by conjugateprior** [comment]
Perhaps you're caching the old one? That page now has some discussion up on how to make item info from your own items, and then about what your vector file should look like and how to point the package at it. There isn't anything extra to say about analysis because it'll be the same statistics function calls as in the replication vignette.

What more were you looking for?

**Comment by peoplecure** [comment]
I see. I guess I will have to play around with it. Thanks for the help!
